spring:
  application:
    name: next-pizza-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/next_pizza
    username: postgres
    password: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true