app:
  jwt:
    secret: next-pizza-secret
    subject: User details
    issuer: next pizza api
#    expiration: 900000
    expiration: 15000
    refresh-expiration: 604800000

spring:
  application:
    name: next-pizza-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/next_pizza
    username: postgres
    password: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true