import type { Metadata } from "next";
import React from "react";
import {Header} from "@/components/shared/header";

export const metadata: Metadata = {
    title: "Next Pizza | Главная",
    description: "Generated by create next app",
};

export default function HomeLayout({
                                       children,
                                       product
                                   }: Readonly<{
    children: React.ReactNode;
    product: React.ReactNode;
}>) {
    return (
        <main className={'min-h-screen'}>
            <Header/>
            {children}
            {product}
        </main>
    );
}
