import React from "react";
import {Metadata} from "next";
import {Container, Header} from "@/components/shared";

export const metadata: Metadata = {
    title: 'Next pizza | корзина',
    description: 'Generated by Next.js',
}

export default function CheckoutLayout(
    {children,}: {
        children: React.ReactNode
    }) {
    return (
        <main className={'min-h-screen bg-[#F4F1EE]'}>
            <Container>
                <Header className={'border-b-gray-200'} hasCart={false} hasSearch={false}/>
                {children}
            </Container>
        </main>
    )
}
