--liquibase formatted sql

--changeset alex:1

CREATE TABLE verification_code
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id) UNIQUE ,
    code varchar(16),
    role varchar(16) DEFAULT 'USER',
    expires_at timestamp DEFAULT now(),
    created_at timestamp DEFAULT (now())
)