--liquibase formatted sql

--changeset alex:1

CREATE TABLE refresh_token
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    token text UNIQUE NOT NULL ,
    expiration_date timestamp,
    user_id int REFERENCES users(id) NOT NULL
)