--liquibase formatted sql

--changeset alex:1

CREATE TABLE orders
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id),
    token text,
    total_amount int NOT NULL ,
    status varchar(16),
    payment_id text,
    items jsonb,
    full_name varchar(128) NOT NULL ,
    email varchar(320) NOT NULL ,
    phone varchar(16) NOT NULL ,
    comment varchar(256),
    created_at timestamp DEFAULT (now()),
    updated_at timestamp
)