--liquibase formatted sql

--changeset alex:1

CREATE TABLE ingredient_product
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    ingredient_id int REFERENCES ingredient(id) NOT NULL ,
    product_id int REFERENCES product(id) NOT NULL ,
    UNIQUE (ingredient_id, product_id)
)