--liquibase formatted sql

--changeset alex:1

CREATE TABLE users
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    full_name varchar(128),
    email varchar(320),
    password varchar(128),
    created_at timestamp DEFAULT (now()),
    updated_at timestamp
)