--liquibase formatted sql

--changeset alex:1

CREATE TABLE cart
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id) UNIQUE ,
    token text NOT NULL ,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp
)