--liquibase formatted sql

--changeset alex:1

CREATE TABLE product
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(128),
    image_url text,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp
)