--liquibase formatted sql

--changeset alex:1

CREATE TABLE product
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(128) NOT NULL ,
    image_url text NOT NULL ,
    category_id int REFERENCES category(id) NOT NULL ,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp
)