--liquibase formatted sql

--changeset alex:1

CREATE TABLE category
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(32) UNIQUE NOT NULL ,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp
)