TRUNCATE TABLE users RESTART IDENTITY CASCADE ;
TRUNCATE TABLE category RESTART IDENTITY CASCADE ;
TRUNCATE TABLE ingredient RESTART IDENTITY CASCADE ;
TRUNCATE TABLE product RESTART IDENTITY CASCADE;
TRUNCATE TABLE ingredient_product RESTART IDENTITY CASCADE ;