TRUNCATE TABLE users RESTART IDENTITY CASCADE ;
TRUNCATE TABLE category RESTART IDENTITY CASCADE ;
TRUNCATE TABLE ingredient RESTART IDENTITY CASCADE ;
TRUNCATE TABLE product RESTART IDENTITY CASCADE;
TRUNCATE TABLE ingredient_product RESTART IDENTITY CASCADE ;
TRUNCATE TABLE product_item RESTART IDENTITY CASCADE ;
TRUNCATE TABLE cart RESTART IDENTITY CASCADE ;
TRUNCATE TABLE cart_item RESTART IDENTITY CASCADE ;
TRUNCATE TABLE cart_item_ingredient RESTART IDENTITY CASCADE ;